# ----------------------------------------
font_family      JetBrainsMono NF
dynamic_background_opacity yes
background            #1d1f21
background_opacity    0.78
cursor_beam_thickness 1.5
window_padding_width 25
scrollback_lines 10000
cursor_shape     beam
font_size        15.5
adjust_line_height 0
bold_is_bright   no
# ----------------------------------------
